<table class="size-chart">
    <thead>
        <tr>
            <th></th>
            <th>XS</th>
            <th>S</th>
            <th>M</th>
            <th>L</th>
            <th>XL</th>
            <th>XXL</th>
            <th>3XL</th>
            <th>4XL</th>
            <th>5XL</th>
            <th>6XL</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Size</td>
            <th>2</th>
            <th>4/6</th>
            <th>8/10</th>
            <th>12/14</th>
            <th>16/18</th>
            <th>20/22</th>
            <th>24/26</th>
            <th>28/30</th>
            <th>32/34</th>
            <th>36/38</th>
        </tr>
        <tr>
            <td>Bust</td>
            <th>32-34</th>
            <th>35-36</th>
            <th>37-38</th>
            <th>39-41</th>
            <th>42-44</th>
            <th>45-47</th>
            <th>45-51</th>
            <th>52-55</th>
            <th>56-69</th>
            <th>60-63</th>
        </tr>
    </tbody>
</table>