import os 

# prod_img_path = '../product-images'
prod_img_path = './temp_prod_img'

color_pairs = {
'hddstysage':'heathereddustysage',
'hthrdcharcoal':'heatheredcharcoal',
'htddstypch':'heathereddustypeach',
'htdlvndr':'heatheredlavender',
'htdteal':'heatheredteal',
'marfrost':'maritimefrost',
'marifrost':'maritimefrost',
'milgrnfst':'militarygreenfrost',
'nvyfrost':'navyfrost',
'prplfrost':'purplefrost',
'turqfrost':'turquoisefrost',
'wstriahthr':'wisteriaheather',
'ltbluenavy':'lightbluenavy',
'petrolblnavy':'petrolbluenavy',
'sftyorg':'safetyorange',
'sftyyellow':'safetyyellow',
'hthrddeeproy':'heathereddeeproyal',
'hthrdred':'heatheredred',
'battleshipgry':'battleshipgrey',
'blackcharhth':'blackcharcoalheather',
'pearlgreyhth':'pearlgreyheather',
'riverblnv':'riverbluenavy',
'nsbldsbnv':'nightskybluedressnavy',
'carolinabl':'carolinablue',
'brtkelgn':'brightkellygreen',
'blkbtlgy':'blackbattleshipgrey',
'dpforgrn':'deepforestgreen',
'dsbnvbtgy':'dressbluenavybattleshipgrey',
'txorange':'texasorange',
'sunflwrylw':'sunfloweryellow',
'trplpink':'tropicalpink',
'mediblue':'mediterraneanblue',
'ultramrnbl':'ultramarineblue',
'charhtgrey':'charcoalheathergrey',
'brtlvndr':'brightlavender',
'clovergrn':'clovergreen',
'pinkrspbry':'pinkraspberry',
'royalblk':'royalblack',
'engnrdbk':'engineredblack',
'blkirgy':'blackirongrey',
'brillblue':'brilliantblue',
'brtpurple':'brightpurple',
'nvbllake':'navybluelake',
'charcoalht':'charcoalheather',
'oxfordhthr':'oxfordheather',
'sterlinggy':'sterlinggrey',
'aquaticbl':'aquaticblue',
'athletichthr':'athleticheather',
'athleticmarn':'athleticmaroon',
'greyhthr':'greyheather',
'athlhthr':'athleticheather',
'marshmllw':'marshmellow',
'navyhthr':'navyheather',
'oaththr':'oatmealheather',
'poprasphtr':'popraspberryheather',
'sftygrn':'safetygreen',
'slickerylw':'slickeryellow',
'dknvhthr':'darknavyheather',
'dkgyhthr':'darkgreyheather',
'dkcharhth':'darkcharcoalheather',
'amthstprpl':'amethystpurple',
'dsblnavy':'dressbluenavy',
'sunfloweryllw':'sunfloweryellow',
'trplpink':'tropicalpink',
'txorange':'texasorange',
'ultramrnbl':'ultramarineblue',
'ultramarnblue':'ultramarineblue',
'violetprpl':'violetpurple',
'whtltstn':'whitelightstone',
'royclsnvy':'royalclassicnavy',
'redltstn':'redlightstone',
'nvltstone':'navylightstone',
'blkltstn':'blacklightstone',
'brtlavender':'brightlavender',
'burgltst':'burgundylightstone',
'dkgreennv':'darkgreennavy',
'charhthrgrey':'charcoalheathergrey',
'lblulstn':'lightbluelightstone',
'lstnclsnv':'lightstoneclassicnavy',
'medblue':'mediterraneanblue',
'autumnorng':'autumnorange',
'dpblackgraph':'deepblackgraphite',
'richreddpbk':'richreddeepblack',
'rvblnvwht':'riverbluenavywhite',
'blkthgrey':'blackthundergrey',
'grphwhite':'graphitewhite',
'rgtblgsgy':'regattabluegustygrey',
'vioprpblk':'violetpurpleblack',
'voltagebl':'voltageblue',
'blwakehtht':'bluewakeheather',
'cobaltht':'cobaltheather',
'dkhtgry':'darkheathergrey',
'dksmkgy':'darksmokegrey',
'dporhthr':'deeporangeheather',
'forestgnht':'forestgreenheather',
'forestgrn':'forestgreen',
'gphheather':'graphiteheather',
'gyconcrete':'greyconcrete',
'mdhtgrey':'mediumheathergrey',
'pkrasht':'pinkraspberryheather',
'scarhthr':'scarletheather',
'teamcard':'teamcardinal',
'trnvyhthr':'truenavyheather',
'turfgrnhtr':'turfgreenheather',
'varprplht' : 'varsitypurpleheather',
'vtghtr' : 'vintageheather',
'athlmaroon' : 'athleticmaroon',
'aquaticbl' : 'aquaticblue',
'athlhthr' : 'athleticheather',
'blkhthr':'blackheather',
'btlgrey':'battleshipgrey',
'coyotebrn':'coyotebrown',
'dkchocbrn':'darkchocolatebrown',
'dpforest':'deepforest',
'dprdhthr': 'deepredheather',
'dslvrhthr':'darksilverheather',
'gustygyhtr':'gustygreyheather',
'htdkchocbr':'heatherdarkchocoaltebrown',
'hthrathmar':'heatherathleticmaroon',
'hthrnavy': 'heathernavy',
'hthrpurple':'heatherpurple',
'hthrred':'heatherred',
'hthrroyal': 'heatherroyal',
'htsangria': 'heathersangria',
'mnmtgrey': 'monumentgrey',
'olvdrabgn': 'olivedrabgreen',
'troyhthr':'trueroyalheather',
'woodlandbr':'woodlandbrown',
'stlgreyltst': 'steelgreylightstone',
'texorngltst': 'texasorangelightstone',
'txorglstn':'texasorangelightstone',
'purpleltstn':'purplelightstone',
'ultramnblue': 'ultramarinenblue',
'smkgychrm': 'smokegreychrome',
'blkchrome': 'blackchrome',
'riverbluenvy': 'riverbluenavy',
'chargrey': 'charcoalgrey',
'chargreyht': 'charcoalgreyheather',
'clsnvltst': 'classicnavylightstone',
'ultramrnblue': 'ultramarineblue',
'darkhthr':'darkheather',
'sorange':'safetyorange',
'htsptdknvy': 'heathersportdarknavy',
'htsptroyal': 'heathersportroyal',
'htsptscar': 'heathersportscarlet',
'prplgrey': 'purplegrey',
'sptscarred': 'sportscarletred',
'sptdknavy': 'sportdarknavy',
'sptdkgreen': 'sportdarkgreen',
'tennorange': 'tennesseeorange',
'troygrey': 'trueroyalgrey',
'agnbagnbh':'aegeanblueaegeanblueheather',
'dpbkchrht': 'deepblackcharcoalheather',
'rvbnrvbnh':'riverbluenavyriverbluenavyheather',
'truebluewht': 'truebluewhite',
'marfrost': 'maroonfrost',
'sldathgrey': 'solidathleticgrey',
'vtgblack': 'vintageblack',
'charitypnk': 'charitypink',
'newportblu': 'newportblue',
'windsorgry': 'windsorgrey',
'gustygreywht': 'gustygreywhite',
'truenavywht': 'truenavywhite',
'trueroyalwht': 'trueroyalwhite',
'hthrpurple':'heatherpurple',
'antquchryred': 'antiquecherryred',
'antqusapphire': 'antiquesapphire',
'heriblue': 'heritageblue',
'blkirgy': 'blackirongrey',
'blktrrd': 'blacktruered',
'blktrroy': 'blacktrueroyal',
'irgywhite': 'irongreywhite',
'trnvwhite': 'truenavywhite',
'celadonbl': 'celadonblue',
'darkgreyhthr': 'darkgreyheather',
'lightgreyhth': 'lightgreyheather',
'trbktrbk': 'trueblacktrueblack',
'trblkgrey': 'trueblackgrey',
'trnvtrnv': 'trueblacktruenavy',
'athlheather': 'athleticheather',
'milgrnhtr': 'militarygreenheather',
'mustardhtr': 'mustardheather',
'oaththr': 'oatmealheather',
'swtcrmhthr': 'sweetcreamheather',
'vntghthrblue': 'vintageheatherblue',
'vntghthrmar': 'vintageheathermaroon',
'vntghthrnavy': 'vintageheathernavy',
'vntghthrred': 'vintageheatherred',
'antqsapphr': 'antiquesapphire',
'antqchryrd': 'antiquecherryred',
'dkchoc':'darkchocolate',
'milgreen':'militarygreen',
'moroccanbl': 'moroccanblue'
}

def rename_color(prod_img_path):
    color_pairs_dict = dict(color_pairs)
    for filename in os.listdir(prod_img_path):
        if filename.endswith(".jpg"):
            try:
                parts = filename.split('_')
                prod_color = parts[0].lower()
                new_filename = f"{color_pairs_dict.get(prod_color, prod_color)}_{parts[1]}"
                if new_filename != filename:
                    os.rename(os.path.join(prod_img_path, filename), os.path.join(prod_img_path, new_filename))
                    print(f"Renaming {filename} to {new_filename}")
            except (FileNotFoundError, PermissionError) as e:
                print(f"Error processing {filename}: {e}")
            except Exception as e:
                print(f"Unexpected error processing {filename}: {e}")

    print("Now run add_sm.py")
rename_color(prod_img_path)
